### ISSUE TITLE
option use-v4-tcp-ports fails

### ISSUE THREAD

**Issue by rharolde** [egberts/bind9_parser#33]
Thanks, this looks useful.  Testing with my config,
Parser choked on:
```
options {
	tcp-clients 1000;
	use-v4-udp-ports {
		1024 65535;
	};
};
```

**Comment by egberts** [comment]
`range` was optional?!  Good catch!

**Comment by egberts** [comment]
Fixed

BTW, that is UDP, not TCP ... I hope.

I couldn't find any `use-v4-tcp-ports` nor `use-v6-tcp-ports`.
