### ISSUE TITLE
TSIG key name should accept dots (again)

### ISSUE THREAD

**Issue by stephan2012** [egberts/bind9_parser#58]
Looks like something went wrong with the issue mentioned in #53 and the fix in https://github.com/egberts/bind9_parser/commit/dd9fe1acdeb74029fa966b15287ba22062de342c: The fix adds the dot to `charset_tls_id_base`, while it should go to `charset_key_id_base` as proposed in my PR https://github.com/egberts/bind9_parser/pull/54.

@egberts Do you want me to submit a new PR?

**Comment by egberts** [comment]
Uargh!

I spent quite a bit of time re-reviewing the syntaxes.  

Now I am unsure. 

Yeah, go ahead.

Might as well do that PR. 

My earlier attempt was to consolidate the variables but even now Ive lost track of who else needs this.  

PR, please, for my prompt acceptance.

**Comment by stephan2012** [comment]
Will do.
