### ISSUE TITLE
please bump pypi version

### ISSUE THREAD

**Issue by mutax** [egberts/bind9_parser#64]
Hey, 
this project is great and will save me a lot of work - thank you for all the effort!

But currently https://pypi.org/project/bind9-parser/ lists version  0.9.8, released: Nov 23, 2019 as latest -- and this version cannot parse my nzf files created by bind. Could you bump the version?

I noticed in order to pip install from git I needed this change to the `pyproject.toml`:

```
 [build-system]
-requires = ["pyparsing >=2.4.5"]
+requires = ["pyparsing >=2.4.5", "setuptools>=40.8.0"]
+build-backend = "setuptools.build_meta:__legacy__"
```

**Comment by egberts** [comment]
I am closing this as 'WontFix' due to PyPi.

But am creating another issue to deal removal from PyPi.
