### ISSUE TITLE
[view] - only the last view is presents when use asDict 

### ISSUE THREAD

**Issue by fccagou** [egberts/bind9_parser#9]
Hello, 

First of all, thanks a lot for your work !

I'm looking a way to make a network graph representation of the bind configuration.
I began to make it using python regex it's not good enough.
Searching for existing bind9 parser, I've found yours and I'm testing it now. 

I know the code is beta, I've found something looking like a bug.

**$ cat test_view.conf** 

```
view "red" {
    zone "z1.com" { };
    zone "z2.com" { };
};

view "green" {
    zone "z3.com" { };
    zone "z4.com" { };
};
```

**Running parser $ ~/src/bind9_parser/examples/parse_bind9.py  test_view.conf** 
```
Start: Is the library quiet?
End: Is the library quiet?
len(result): 2

Plain print(result):
[['"red"', [['"z1.com"'], ['"z2.com"']]],
 ['"green"', [['"z3.com"'], ['"z4.com"']]]]
result: {'view': [{'view_name': '"green"', 'configs': {'zone': {'zone_name': '"z4.com"'}}}]}

print(result.asDict()):
{   'view': [   {   'configs': {   'zone': {   'zone_name': '"z4.com"'}},
                    'view_name': '"green"'}]}
end of result.

```
The red view is present in result but absent in the dict format.

Thanks in advance for informations.

-- François

**Comment by egberts** [comment]
I knew I would run into something complex, but never something so simple as a multiple view.  This is a design error on my part.  

Some meatball surgery will be required to somehow make it accessible by mycfg[‘view’][‘trusted’] python 

At the moment, it looks easiest to put mycfg[‘view’][0] so I need to get in touch with the designer of the engine.

**Comment by egberts** [comment]
this is a major bug and a show stopper for majority of Bind9 configuration.  

I’ve asked the pyparsing maintainer on how to get recurring and subsequential`view` records to get item-appended to a Python dictionary `view` variable.

**Comment by egberts** [comment]
Fixed it.

**Comment by egberts** [comment]
Basically, I've elected to do `list` for the views (and zones) and each view(/zone) has its own `dict` .
